name: Continuous Delivery

on:
  pull_request:
    branches:
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Frontend Images
        run: npm i
      - name: Run Frontend Deployment to GH Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/igormcsouza/english-class.git
          npm run deploy -- --user "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
